// react-demo/src/components/baseUse/ListDemo.js
import React from "react";

class ListDemo extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      list: [
        {
          id: "id-1",
          title: "标题1",
        },
        {
          id: "id-2",
          title: "标题2",
        },
        {
          id: "id-3",
          title: "标题3",
        },
      ],
    };
  }
  render() {
    return (
      <ul>
        {
          this.state.list.map((item,index) => <li key={item.id}>index: {index} - {item.title}</li>)
        }
      </ul>
    );
  }
}

export default ListDemo;

// vue-demo/src/components/BaseUse/ListDemo.vue
<template>
  <div class="">
    <p>遍历数组</p>
    <ul>
      <li v-for="(item, index) in listArr" :key="item.id">
        {{ index }} - {{ item.id }} - {{ item.title }}
      </li>
    </ul>
    <p>遍历对象</p>
    <ul>
      <li v-for="(val, key, index) in listObj" :key="key">
        {{ index }} - {{ key }} - {{ val.title }}
      </li>
    </ul>
  </div>
</template>

<script>
export default {
  data () {
    return {
      listArr: [
        {
          id: 'a', title: '标题1'
        },
        {
          id: 'b', title: '标题2'
        },
        {
          id: 'c', title: '标题3'
        }
      ],
      listObj: {
        a: { title: '标题1' },
        b: { title: '标题2' },
        c: { title: '标题3' }
      }
    }
  }
}
</script>

<style scoped></style>
